<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [6]:
%%sql

select table_name from
information_schema.tables where
table_schema = 'public';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

In [25]:
%%sql

select now();

# Select Extract(month from now());

select date_trunc('year', now());

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

1 rows affected.

                 date_trunc
0 2026-01-01 00:00:00+00:00

In [29]:
%%sql

select  column_name from
information_schema.columns where
table_name = 'sales';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

13 rows affected.

     column_name
0   exchangerate
1     linenumber
2      orderdate
3   deliverydate
4    customerkey
5       storekey
6     productkey
7       quantity
8      unitprice
9       netprice
10      unitcost
11      orderkey
12  currencycode

In [30]:
%%sql

select
    date_trunc('month', orderdate)::date as order_month,
    sum(quantity * netprice * exchangerate) as total_sales_monthly,
    count(Distinct customerkey) as customer_count
from sales
group by
    order_month
order by
    order_month
limit 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  order_month  total_sales_monthly  customer_count
0  2015-01-01            384092.66             200
1  2015-02-01            706374.12             291
2  2015-03-01            332961.59             139
3  2015-04-01            160767.00              78
4  2015-05-01            548632.63             236
5  2015-06-01            748563.97             238
6  2015-07-01            635376.13             227
7  2015-08-01            718538.62             235
8  2015-09-01            696805.68             277
9  2015-10-01            824891.22             304